### ISSUE TITLE
 Cannot resolve dependency 'rmc-steps'

### ISSUE THREAD

**Issue by heymind** [react-component/m-steps#1]
```
×  D:\workspace\dfeed-zone\node_modules\antd-mobile\lib\steps\index.js:31:24: Cannot resolve dependency 'rmc-steps'
  29 | var _react2 = _interopRequireDefault(_react);
  30 |
> 31 | var _rmcSteps = require('rmc-steps');
     |                         ^
  32 |
  33 | var _rmcSteps2 = _interopRequireDefault(_rmcSteps);
  34 |
```

```
  "main": "./lib/index",
  "module": "./es/index", //<----------------------------------(this line)----
  "files": [
    "lib",
    "assets/iconfont.css",
    "assets/index.css"
  ],
```
But there's no folder called `es`.It's all right when I remove 'this line' above.
![image](https://user-images.githubusercontent.com/11583541/36244900-39155a84-1263-11e8-97d7-d2f6af24d930.png)

**Comment by cncolder** [comment]
friendly ping @silentcloud 

这个 module 字段确实会引起一些问题, 例如 [parcel](https://github.com/parcel-bundler/parcel) 目前就无法打包 antd-mobile.

ref parcel-bundler/parcel#1422

**Comment by qwIvan** [comment]
@cncolder 遇到相同问题

**Comment by healim** [comment]
I fixed the bug by downgrading `ant-design-mobile` version to `"antd-mobile": "~2.2.3",` (latest version is 2.2.4).
ref [Modal cannot input anything #2285](https://github.com/ant-design/ant-design-mobile/issues/2285)

**Comment by silentcloud** [comment]
Sorry for this. bump 1.0.1
